name: Deploy

on:
  push:
    branches: [ "release" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build artifacts
      run: cargo build --release --verbose
